[package]
name = "c2rust-xcheck-plugin"
description = "rustc compiler plugin used by C2Rust cross-checking"
version = "0.1.0"
authors = ["The C2Rust Development Team <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
readme = "README.md"

[lib]
plugin = true

[features]
expand-macros = []
c-hash-functions = []

[dependencies]
matches = "0.1.6"
serde = "1.0"
serde_yaml = "0.7"
c2rust-xcheck-config = { path = "../config", features = ["parse-syntax", "scopes"] }

[dev-dependencies]
c2rust-xcheck-derive = { path = "../derive-macros" }
c2rust-xcheck-runtime = { path = "../runtime" }
