[package]
name = "cross-check-plugin"
version = "0.1.0"
authors = ["Andrei Homescu <ah@immunant.com>"]
readme = "README.md"

[lib]
plugin = true

[features]
xcheck-args = []

[dependencies]
config = { path = "../config" }
