os: osx
osx_image: xcode9.3 # request macOS 10.13
sudo: enabled
language: generic

# TODO: figure out why submodule checkout fails
git:
  submodules: false

env:
  global:
    - PATH="/usr/local/opt/ccache/libexec:$PATH"
    - CXX=clang++
    - CC=clang
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_CPP2=1

# https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache
cache: 
  directories: # handle non-obvious Rust target dirs
    - $HOME/.rustup
    - $HOME/.cargo
    - $HOME/.ccache
    - $HOME/Library/Caches/Homebrew
    - $TRAVIS_BUILD_DIR/ast-importer/target.travis
    - $TRAVIS_BUILD_DIR/cross-checks/rust-checks/config/target
    - $TRAVIS_BUILD_DIR/cross-checks/rust-checks/rustc-plugin/target
    - $TRAVIS_BUILD_DIR/cross-checks/rust-checks/runtime/target
    - $TRAVIS_BUILD_DIR/cross-checks/rust-checks/derive-macros/target
    - $TRAVIS_BUILD_DIR/rust-refactor/target

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade python
  - ./scripts/provision_mac.sh
  - . ~/.cargo/env

# NOTE: travis doesn't automatically terminate if command fails.
script: 
  - ccache -s
  - python3 ./scripts/build_translator.py  || travis_terminate 1
  - python3 ./scripts/test_translator.py ./tests || travis_terminate 1
 # NOTE: disabled because it takes to long to compile on free plan :/
 # To enable, add `--with-clang` to build_translator.py line above.
 # - python3 ./scripts/build_cross_checks.py || travis_terminate 1
 # - python3 ./scripts/test_cross_checks.py || travis_terminate 1
  - ccache -s

notifications:
  slack:
    secure: hNFCy0vOl/x5+O+6LOhwkpizPnNTpdLJet7gJZ4RpOPMTFWDblTnou93VVI3lOUWH+JkuYhv9qik6xBQtHtg/Ijhw/oNd0NUOLaiA5en+unSeAiKarJfjA1TToySPy4f+9bYzPGYp/gooCXkQPOXSe57/4o0Tn2aelCn8MccdadkIxqJajA8DBtSu1iHk6DnQCldxeN5DfezXBTl+NtCbY/YftVR+3T8qeMKzIdpWdWKM0ELx6uTG/6KhPEe51KWNjh+1ZMiWz9QL5D82k7ihm7aS8wpMR/uDwr3HdJIMT9gBw97eIDVCX8QkkB4BkMehOgK5+eBq/QaQpqn3ULSokFdVJSsyiv9mxfkGbXQA/MWsqU2PdzpCnr+9XQy2b3e1GddSMSShzvWtihqtVkjw9R5D0581W3swdxhGGgTifYcC4vf4BhJbLk5evr9PouqYf7ZijLWG7ReBKsS0M24DrW2Wk77zxNVskrHOXUEb7bPv88nmqA/P8VUGyKjRdWR+1ZmR20aJVo6ZQW7Z61erKuX3xQDi9tEDDlw4JhTKzR2eamwdwf1Ep1vI61dBG+KwyKVaqX7u067pecj3/f++ZrVF1vOqC+te4qNjoa3ABrfjIE1tk2aJEVdLHnSoBXXzOpijs3JzrEQJTYRbXW8KXPdEqqHFV/Z/+1Mnmr6MkQ=
    on_success: change
    on_failure: always
  email: false
