trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md
    - LICENSE
    - .travis.yml
    - book.toml
    - docker/*
    - vagrant/*
    - manual/*
    - docs/*

jobs:
- job: LinuxTests
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      arch:
        containerImage: immunant/c2rust:base-archlinux-20190206
        env: 
      debian8:
        containerImage: immunant/c2rust:debian-jessie-20190206
      debian9:
        containerImage: immunant/c2rust:debian-stretch-20190206
      ubuntu16:
        containerImage: immunant/c2rust:ubuntu-xenial-20190206
      ubuntu18:
        containerImage: immunant/c2rust:ubuntu-bionic-20190206
  container: $[ variables['containerImage'] ]
  steps:
  - script: |
      # rust was installed for the `docker` user, not the user azure creates
      # but cargo and rustup can be controlled via $CARGO_HOME and $RUSTUP_HOME.
      # NOTE: $HOME is not set correctly for the azure user; don't rely on it.
      export PATH="/home/docker/.cargo/bin:$PATH"
      export RUSTUP_HOME=/home/docker/.rustup
      export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
      cargo build
    displayName: 'Fast build against host clang/LLVM'

  - script: |
      export PATH="/home/docker/.cargo/bin:$PATH"
      export RUSTUP_HOME=/home/docker/.rustup
      export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
      python3 ./scripts/test_translator.py --debug ./tests
    displayName: 'Test translator (fast build)'

  - script: |
      export PATH="/home/docker/.cargo/bin:$PATH"
      export RUSTUP_HOME=/home/docker/.rustup
      export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
      cargo clean
    displayName: 'Clean'

  - script: |
      export PATH="/home/docker/.cargo/bin:$PATH"
      export RUSTUP_HOME=/home/docker/.rustup
      export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
      python3 ./scripts/build_translator.py --debug
    displayName: 'Developer build against local clang/LLVM'

  - script: |
      export PATH="/home/docker/.cargo/bin:$PATH"
      export RUSTUP_HOME=/home/docker/.rustup
      export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
      python3 ./scripts/test_translator.py --debug ./tests
    displayName: 'Test translator (dev build)'

- job: DarwinTests
  pool:
    vmImage: 'macos-10.13'
  steps:
  - script: |
      ./scripts/provision_mac.sh
    displayName: 'Provision macOS'

  - script: |
      source $HOME/.cargo/env
      cargo build
    displayName: 'Fast build against host clang/LLVM'

  - script: |
      source $HOME/.cargo/env
      python3 ./scripts/test_translator.py --debug ./tests
    displayName: 'Test translator (fast build)'
