trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md
    - LICENSE
    - .travis.yml
    - book.toml
    - docker/*
    - vagrant/*
    - manual/*
    - docs/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 23E7166788B63E1E
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6B05F25D762E3157
    sudo apt-get update
    sudo scripts/provision_deb.sh

  displayName: 'Run Debian provisioning script.'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
