trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md
    - LICENSE
    - .travis.yml
    - book.toml
    - docker/*
    - vagrant/*
    - manual/*
    - docs/*

pool:
  vmImage: 'Ubuntu-16.04'

container: 
  image: immunant/c2rust:ubuntu-bionic-20190131
  # options: --privileged

steps:
- script: |
    echo $HOME
    ls $HOME
    uname -a


  displayName: 'Provision required packages'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
