trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md
    - LICENSE
    - .travis.yml
    - book.toml
    - docker/*
    - vagrant/*
    - manual/*
    - docs/*

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:
    debian8:
      containerImage: immunant/c2rust:debian-jessie-20190202
    debian9:
      containerImage: immunant/c2rust:debian-stretch-20190201
    ubuntu16:
      containerImage: immunant/c2rust:ubuntu-xenial-20190201
    ubuntu18:
      containerImage: immunant/c2rust:ubuntu-bionic-20190201

container: $[ variables['containerImage'] ]

steps:
- script: |
    # rust was installed for the `docker` user, not the user azure creates
    # but cargo and rustup can be controlled via $CARGO_HOME and $RUSTUP_HOME.
    # NOTE: $HOME is not set correctly for the azure user; don't rely on it.
    export PATH="/home/docker/.cargo/bin:$PATH"
    export RUSTUP_HOME=/home/docker/.rustup
    export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
    cargo build
  displayName: 'Build C2Rust against host clang/LLVM'

- script: |
    export PATH="/home/docker/.cargo/bin:$PATH"
    export RUSTUP_HOME=/home/docker/.rustup
    export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
    python3 ./scripts/test_translator.py --debug ./tests
  displayName: 'Test C2Rust translator'
