trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md
    - LICENSE
    - .travis.yml
    - book.toml
    - docker/*
    - vagrant/*
    - manual/*
    - docs/*

pool:
  vmImage: 'Ubuntu-16.04'

container: 
  image: immunant/c2rust:ubuntu-bionic-20190131
  # options: --privileged

steps:
- script: |
    . ~/.cargo/env
    cargo build
  displayName: 'Build C2Rust against host clang/LLVM'

- script: |
    python3 ./scripts/test_translator.py --debug ./tests
  displayName: 'Test C2Rust translator'
