[book]
title = "C2Rust Manual"
src = "manual/"

[build]
create-missing = false
preprocess = ["links", "index", "include_md", "generator_dispatch"]

[preprocessor.include_md]
command = "cargo run --bin mdbook-include_md --quiet --"

[preprocessor.generator_dispatch]
command = "python3 manual/preprocessors/generator_dispatch.py"
