[workspace]
members = [
    "c2rust",
    "c2rust-transpile",
    "c2rust-refactor",
    "c2rust-ast-builder",
    "c2rust-ast-exporter",
    "manual",
]
exclude = [
    "cross-checks/rust-checks",
    "examples",
]
