[workspace]
members = [
    "config",
    "config-capi",
    "derive-macros",
    "runtime",
    "rustc-plugin",
    "backends/fakechecks-zstd",
    "backends/libclevrbuf-sys",
    "backends/libfakechecks-sys",
    "backends/dynamic-dlsym",
]
default-members = [
    "config",
    "derive-macros",
    "runtime",
    "rustc-plugin",
    "backends/fakechecks-zstd",
    "backends/dynamic-dlsym",
]
exclude = [
    "tests"
]
