[workspace]
members = [
    "config",
    "derive-macros",
    "runtime",
    "rustc-plugin",
    "libclevrbuf-sys",
    "libfakechecks-sys",
]
default-members = [
    "config",
    "derive-macros",
    "runtime",
    "rustc-plugin",
]
exclude = [
    "tests"
]
