[package]
name = "c2rust"
version = "0.0.0"
authors = ["Galois, Inc., Immunant, Inc."]
description = "The C2Rust Project"
license = "BSD-3-Clause"
homepage = "https://c2rust.com"
repository = "https://github.com/immunant/c2rust"

[dependencies]
