[package]
name = "c2rust-refactor"
version = "0.1.0"
authors = [
  "The C2Rust Project Developers <c2rust@immunant.com>",
  "Stuart Pernsteiner <spernsteiner@galois.com>",
]
build = "build.rs"

[dependencies]
diff = "0.1.10"
json = "0.11.8"
libc = "0.2.28"
regex = "0.2.2"
ena = "0.7.3"
c2rust-ast-builder = { path = "../c2rust-ast-builder" }
indexmap = { version = "1.0.1", features = ["serde-1"] }
cargo = "0.30.0"
clap = {version = "~2.32.0", features = ["yaml"]}

[lib]
name = "c2rust_refactor"
path = "src/lib.rs"
