[package]
name = "c2rust-xcheck-derive"
description = "Derive crate for #[derive(XCheckHash)] used by C2Rust cross-checking"
version = "0.1.0"
authors = ["The C2Rust Development Team <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
c2rust-xcheck-config = { path = "../config", features = ["parse-syn", "with-quote"] }
syn = { version = "0.11.11", features = ["full", "visit"] }
synstructure = "0.6.1"
quote = "0.3.15"

[dev-dependencies]
c2rust-xcheck-runtime = { path = "../runtime" }
