[book]
title = "C2Rust Manual"
src = "docs"

[build]
create-missing = false
preprocess = ["links", "index", "include_md"]

[preprocessor.include_md]
command = "cargo run --bin mdbook-include_md --quiet --"
