[package]
name = "c2rust-xcheck-config-capi"
version = "0.1.0"
authors = ["Andrei Homescu <ah@immunant.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
serde = { version = "1.0", features = ["rc"] }
serde_yaml = "0.7"
c2rust-xcheck-config = { path = "../config", features = ["scopes"] }
